cp "$HOME/.config/nvim/init.vim" ".config/nvim/init.vim"
cp "$HOME/.local/share/nvim/site/autoload/plug.vim" ".local/share/nvim/site/autoload/plug.vim"
cp "$HOME/.gitignore_global" ".gitignore_global"
cp "$HOME/.tmux.conf" ".tmux.conf"
cp "$HOME/.zshrc" ".zshrc"
